version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: game_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: arg1
      MYSQL_USER: gameuser
      MYSQL_PASSWORD: gamepassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - game_network

  api:
    build: .
    container_name: game_api
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mysql
      DB_USER: gameuser
      DB_PASSWORD: gamepassword
      DB_NAME: arg1
    depends_on:
      - mysql
    networks:
      - game_network
    volumes:
      - ./app:/app

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: game_streamlit
    ports:
      - "8501:8501"
    environment:
      API_URL: http://api:8000
    depends_on:
      - api
    networks:
      - game_network

networks:
  game_network:
    driver: bridge

volumes:
  mysql_data: